(function(a){a.webshims=a.webshims||{ready:function(a,e){e()},addReady:function(b){a(function(){b(document,a([]))})}};var i=a.webshims;if(!window.Modernizr||!("opacity"in Modernizr))a("html").addClass(a.support.opacity?"opacity":"no-opacity");if(!a.fn.callProp)a.fn.callProp=function(b,e){var r;e||(e=[]);this.each(function(){var c=a.prop(this,b);if(c&&c.apply&&(r=c.apply(this,e),void 0!==r))return!1});return void 0!==r?r:this};var l={},p={};a.jme={version:"2.0.0",classNS:"",options:{},plugins:{},data:function(b,
e,c){b=a(b).data(g+"jme")||a.data(b,g+"jme",{});if(void 0===c)return e?b[e]:b;b[e]=c},registerPlugin:function(a,e){this.plugins[a]=e;if(!e.nodeName)e.nodeName="";if(!e.className)e.className=a},defineMethod:function(a,e){p[a]=e},defineProp:function(b,e){if(!e.set)e.set=e.readonly?function(){throw b+" is readonly";}:a.noop;if(!e.get)e.get=function(e){return a.jme.data(e,b)};l[b]=e},prop:function(b,e,c){if(!l[e])return a.prop(b,e,c);if(void 0===c)return l[e].get(b);var d=l[e].set(b,c);void 0===d&&(d=
c);"noDataSet"!=d&&a.jme.data(b,e,d)}};a.fn.jmeProp=function(b,e){return a.access(this,b,e,!0,a.jme.prop)};a.fn.jmeFn=function(a){var e=Array.prototype.slice.call(arguments,1),c;this.each(function(){c=p[a].apply(this,e);if(void 0!==c)return!1});return void 0!==c?c:this};var m,k=[],g="",c=function(){if(!m)g=a.jme.classNS,m="div."+g+"mediaplayer",a.each(a.jme.plugins,function(b,e){e.className=g+e.className;e.selector=e.nodeName+"."+e.className;k.push(e.selector);g&&e.pseudoClasses&&a.each(e.pseudoClasses,
function(a,b){e.pseudoClasses[a]=g+b})}),k=k.join(",")},f={emptied:1,pause:1};a.jme.getDOMList=function(b){var e=[];b||(b=[]);"string"==typeof b&&(b=b.split(" "));a.each(b,function(a,b){b&&(b=document.getElementById(b))&&e.push(b)});return e};"labels"in document.createElement("input")||i.ready("dom-support",function(){i.defineNodeNamesProperty&&i.defineNodeNamesProperty("button, input, keygen, meter, output, progress, select, textarea","labels",{prop:{get:function(){var b=[],e=this.id;e&&(b=a('label[for="'+
e+'"]'));b[0]||(b=a(this).closest("label",this.form));return b[0]?b.get():null},writeable:!1}})});a.jme.getButtonText=function(b,e){var c=a("span.jme-text, +label span.jme-text",b),d=b.prop("labels");d&&(d=a(d));c[0]||(c=d||b);var f=c.text().split("/"),h=b.prop("title").split("/"),g,j,q,o;2==f.length&&(f[0]=f[0].trim(),f[1]=f[1].trim(),j=!0);2==h.length&&(h[0]=h[0].trim(),h[1]=h[1].trim(),q=!0);b.is('[type="checkbox"], [type="radio"]')?(b.prop("checked",function(){return this.defaultChecked}),g=!0):
b.is("a")&&b.bind("click",function(a){a.preventDefault()});return function(h){o!==h&&(o=h,j&&c.text(f[h||0]),q&&(b.prop("title",f[h||0]),d&&d.prop("title",f[h||0])),e&&b.removeClass(e[h?0:1]).addClass(e[h]),g&&(b.prop("checked",!!h),(b.data("checkboxradio")||{refresh:a.noop}).refresh()))}};a.fn.jmePlayer=function(b){var e=["idle","playing","ended","waiting","mediaerror"].map(function(a){return g+"state-"+a}).join(" ");return this.each(function(){b&&a.jme.data(this,a.extend(!0,{},b));var c=a("audio, video",
this).filter(":first"),d=a(this),n=a(k,d),h=a.jme.getDOMList(a.jme.data(this,"controls")),n=n.add(a(h)),h=a.jme.data(this),s=a.jme.data(c[0]),j,q;s.player=d;s.media=c;if(!h.media){q=!0;j=function(b){var b=b.type,c;if("ended"==b||a.prop(this,"ended"))b="ended";"updateJMEState"==b&&(b=a.prop(this,"readyState"),c=a.prop(this,"paused"),b=!c&&3>b?"waiting":!c&&2<b?"playing":"idle");f[b]&&(b="idle");d.removeClass(e).addClass(g+"state-"+b)};h.media=c;h.player=d;c.bind("ended",function(){c.callProp("pause")}).bind("emptied waiting playing ended pause mediaerror",
j).bind("volumechange updateJMEState",function(){d[a.prop(this,"muted")?"addClass":"removeClass"](g+"state-muted")}).bind("emptied updateJMEState play playing waiting",function(b){var e;"emptied"==b.type?e="addClass":"play"==b.type||"waiting"==b.type||"playing"==b.type?e="removeClass":a.prop(this,"paused")&&(e="addClass");d[e](g+"state-initial")});var o,i;d.bind("useractive",function(){d.addClass(g+"useractive")}).bind("userinactive",{idletime:3500},function(){d.removeClass(g+"useractive")}).bind("focusin",
function(){clearTimeout(o);d.addClass(g+"focusenter")}).bind("focusout",function(){clearTimeout(o);o=setTimeout(function(){d.removeClass(g+"focusenter")},1)}).bind("mouseenter focusin",function(){clearTimeout(i);d.addClass(g+"fover")}).bind("mouseleave focusout",function(){clearTimeout(i);i=setTimeout(function(){d.removeClass(g+"fover")},1)})}d.jmeFn("addControls",n);q&&(h.controlbar&&d.jmeProp("controlbar",!0),j&&c.bind("updateJMEState",j).triggerHandler("updateJMEState"))})};a.jme.defineProp("isPlaying",
{get:function(b){return!a.prop(b,"ended")&&!a.prop(b,"paused")&&1<a.prop(b,"readyState")&&!a.data(b,"mediaerror")},readonly:!0});a.jme.defineProp("player",{get:function(){return a.jme.data(this,"player")||null},readonly:!0});a.jme.defineProp("media",{get:function(){return a.jme.data(this,"media")||null},readonly:!0});a.jme.defineProp("srces",{get:function(b){var b=a.jme.data(b),e=b.media.prop("src"),c=[];return e?[{src:e}]:c=a.map(a("source",b.media).get(),function(b){var e={src:a.prop(b,"src")},
c=a.attr(b,"media");if(c)e.media=c;if(c=a.attr(b,"type"))e.type=c;return e})},set:function(b,e){var c=a.jme.data(b),d=function(b,e){"string"==typeof e&&(e={src:e});a(document.createElement("source")).attr(e).appendTo(c.media)};c.media.removeAttr("src").find("source").remove();a.isArray(e)?a.each(e,d):d(0,e);setTimeout(function(){c.media.callProp("load")},0);return"noDataSet"}});a.jme.defineMethod("togglePlay",function(){a(this).callProp(l.isPlaying.get(this)?"pause":"play")});a.jme.defineProp("controlbar",
{set:function(b,e){var e=!!e,c=a.jme.data(b),d=a("div.jme-default-media-overlay, div.jme-default-control-bar",c.player),f=a.jme.plugins["media-controls"],h="";e&&!d[0]?c._controlbar?c._controlbar.appendTo(c.player):(c.media.prop("controls",!1),a.each(f.pluginOrder,function(b,e){var c=a.jme.plugins[e];c&&c.structure?h+=c.structure.replace("{%class%}",g+e).replace("{%text%}",c.text||""):e&&-1!=e.indexOf("<")&&(h+=e)}),c._controlbar=a(f.barStructure),d=c._controlbar.find("div.jme-cb-box").addClass(g+
"media-controls"),f=c._controlbar.filter("div.jme-default-media-overlay").addClass(g+"play-pause"),f=f.add(d),f=f.add(a(h).appendTo(d)),c._controlbar.appendTo(c.player),c.player.jmeFn("addControls",f)):e||d.detach();f=d=null;return e}});a.jme.defineMethod("addControls",function(b){var e=a.jme.data(this)||{};e.media&&(b=a(b),a.each(a.jme.plugins,function(c,d){b.filter("."+d.className).add(b.find("."+d.className)).each(function(){var b=a(this),c=a.jme.data(this);c.player=e.player;c.media=e.media;if(!c.rendered)c.rendered=
!0,d.options&&a.each(d.options,function(a,b){a in c||(c[a]=b)}),d._create(b,e.media,e.player,c),b=null})}),e.player.triggerHandler("controlsadded"))});a.jme.defineMethod("updateControlbar",function(){var b=a("."+a.jme.classNS+"time-slider",this);if(b[0]&&"absolute"!==b.css("position")){var c=b.parent().width(),d=0;b.siblings().each(function(){this!==b[0]&&"absolute"!==a.css(this,"position")&&(d+=Math.floor(a(this).outerWidth(!0)))});b.width(c-d-(b.outerWidth(!0)-b.width())-0.5)}});a.jme.registerPlugin("media-controls",
{pluginOrder:'play-pause,<div class="media-bar">,currenttime-display,time-slider,duration-display,<div class="volume-controls">,mute-unmute,volume-slider,</div>,fullscreen,</div>'.split(","),barStructure:'<div class="jme-default-media-overlay"></div><div class="jme-default-control-bar"><div class="jme-cb-box"></div></div>',_create:function(a,c,d){var f,n=function(){clearTimeout(f);a.jmeFn("updateControlbar");f=setTimeout(function(){a.jmeFn("updateControlbar")},9)};setTimeout(function(){c.bind("loadedmetadata volumechange play pause ended emptied",
n);d.bind("updatetimeformat controlsadded playerdimensionchange",n)},1);n()}});(function(){var b={add:function(b,c,d){var f=a.data(b,"jmeuseractivity")||a.data(b,"jmeuseractivity",{idletime:2500,idle:!0,trigger:{}}),h=a(b),g=function(){if(!f.idle)f.idle=!0,f.trigger.userinactive&&h.trigger("userinactive")},j,i,b=function(a){if(a&&!("mousemove"===a.type&&a.pageX===j&&a.pageY===i)){if("mousemove"===a.type)j=a.pageX,i=a.pageY;f.idleTimer&&clearTimeout(f.idleTimer);f.idleTimer=setTimeout(g,f.idletime);
if(f.idle)f.idle=!1,f.trigger.useractive&&h.trigger("useractive")}};f.idletime=(c||{}).idletime||f.idletime;if(c&&"idle"in c)f.idle=c.idle;f.trigger[d]=!0;if(!f.bound)h.bind("mouseleave.jmeuseractivity",g).bind("mousemove.jmeuseractivity focusin.jmeuseractivity mouseenter.jmeuseractivity keydown.jmeuseractivity keyup.jmeuseractivity mousedown.jmeuseractivity",b),f.bound=!0;f.idle||b({type:"initunidled"})},remove:function(b,c){var d=a.data(b,"jmeuseractivity")||a.data(b,"jmeuseractivity",{idletime:2500,
idle:!0,trigger:{}});d.trigger[c]=!1;if(!d.trigger.useractive&&!d.trigger.userinactive)a(b).unbind(".jmeuseractivity"),d.bound=!1}};a.each(["useractive","userinactive"],function(c,d){a.event.special[d]={setup:function(a){b.add(this,a,d)},teardown:function(){b.remove(this,d)}}})})();var d=function(b,c){a("video, audio",b).add(c.filter("video, audio")).filter("[data-muted]").each(function(){a.prop(this,"muted",!0)}).end().filter("[data-volume]").each(function(){var b=a(this).data("volume");1>=b&&0<=
b&&a.prop(this,"volume",b)});a(m,b).add(c.filter(m)).jmePlayer()};a(function(){c();d(document,a([]))});i.ready("mediaelement",function(){i.addReady(function(a,c){a!==document&&d(a,c)})})})(jQuery);
(function(a){function i(a,f){var d,b,e;return{get:function(){return e?void 0:a.apply(this,arguments)},set:function(){clearTimeout(d);clearTimeout(b);var a=this,c=arguments;e=!0;d=setTimeout(function(){f.apply(a,c);b=setTimeout(function(){e=!1},30)},0)}}}var l={play:1,playing:1},p=function(){a.webshims.loader&&(a.webshims.loader.loadList(["jquery-ui"]),a.webshims.modules["input-widgets"].src&&a.webshims.loader.loadList(["input-widgets"]))};a.jme.registerPlugin("play-pause",{pseudoClasses:{play:"state-paused",
pause:"state-playing"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"play / pause",_create:function(c,f){var d=a.jme.getButtonText(c,[this.pseudoClasses.play,this.pseudoClasses.pause]);f.bind("play playing ended pause updateJMEState",function(a){a=a.type;a="updateJMEState"==a?f.jmeProp("isPlaying")?1:0:l[a]?1:0;d(a)}).triggerHandler("updateJMEState");c.bind(c.is("select")?"change":"click",function(){f.jmeFn("togglePlay")})}});
a.jme.registerPlugin("mute-unmute",{pseudoClasses:{mute:"state-mute",unmute:"state-unmute"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"mute / unmute",_create:function(c,f){var d=a.jme.getButtonText(c,[this.pseudoClasses.mute,this.pseudoClasses.unmute]);f.bind("volumechange updateJMEState",function(){d(f.prop("muted")?1:0)}).triggerHandler("updateJMEState");c.bind(c.is("select")?"change":"click",function(){f.prop("muted",
!f.prop("muted"))})}});var m=function(c){var f=function(){if(!a.fn._uiSlider)!a.mobile||!a.mobile.slider?a.fn._uiSlider=a.fn.slider:a.widget("jme._uiSlider",a.ui.slider.prototype);c()};a.webshims.ready("jquery-ui",function(){!a.ui||!a.ui.slider?a.webshims.ready("input-widgets",f):f()})};a.jme.registerPlugin("volume-slider",{structure:'<div  class="{%class%}"></div>',_create:function(a,f){p();var d=i(function(){var b=f.prop("volume");void 0!==b&&a._uiSlider("value",b)},function(a){f.prop({muted:!1,
volume:a})});m(function(){a._uiSlider({range:"min",max:1,step:0.05,value:f.prop("volume"),slide:function(a,c){a.originalEvent&&d.set(c.value)}});f.bind("volumechange",d.get)})}});a.jme.registerPlugin("time-slider",{structure:'<div  class="{%class%}"></div>',options:{format:["mm","ss"]},_create:function(c,f,d){p();var b=i(function(){var a=f.prop("currentTime");isNaN(a)||c._uiSlider("value",a)},function(a){try{f.prop("currentTime",a)}catch(b){}});d.jmeFn("addControls",a('<div class="'+a.jme.classNS+
'buffer-progress" />').prependTo(c));m(function(){var a=f.prop("duration");c._uiSlider({range:"min",max:a||1,disabled:!a,step:0.1,value:f.prop("currentTime"),slide:function(a,c){a.originalEvent&&b.set(c.value)}});f.bind({timeupdate:b.get,emptied:function(){c._uiSlider("option","disabled",!0)},durationchange:function(){c._uiSlider("option","disabled",!1)._uiSlider("option","max",f.prop("duration"))}})})}});a.jme.defineMethod("concerningRange",function(c,f){var d={start:0,end:0};c||(c="buffered");c=
a.prop(this,c);null==f&&(f=a.prop(this,"currentTime"));if(!c||!("length"in c))return d;for(var b=0,e=c.length;b<e&&!(d.start=c.start(b),d.end=c.end(b),d.start<=f&&d.end>=f);b++);return d});a.jme.defineProp("progress",{get:function(c){c=a.jme.data(c);if(!c.media)return 0;c=100*(c.media.jmeFn("concerningRange").end/c.media.prop("duration"));99.4<c&&(c=100);return c||0},readonly:!0});a.jme.registerPlugin("buffer-progress",{_create:function(c,f,d,b){var e=a('<div class="'+a.jme.classNS+'buffer-progress-indicator" />').appendTo(c),
c=function(){var a=f.jmeProp("progress");if(b.progress!==a)b.progress=a,e.css("width",a+"%")};f.bind({progress:c,emptied:function(){e.css("width",0);b.progress=0},playing:c});c()}});var k={hh:6E4,mm:60,ss:1,ms:0.0010},g=function(c,f){var d;f||(f=["mm","ss"]);null==c&&(d=a.jme.data(this),c=a.prop(d.media,"duration"));c||(c=0);d=[];for(var b,e=0,g=f.length;e<g;e++)"ms"==f[e]&&e==g-1?b=Math.round(c/k[f[e]]/10):(b=parseInt(c/k[f[e]],10),c%=k[f[e]]),10>b&&(b="0"+b),d.push(b);return d.join(":")};a.jme.defineMethod("formatTime",
g);a.jme.defineProp("format",{set:function(c,f){a.isArray(f)||(f=f.split(":"));var d=a.jme.data(c);d.format=f;a(c).triggerHandler("updatetimeformat");d.player.triggerHandler("updatetimeformat");return"noDataSet"}});a.jme.registerPlugin("duration-display",{structure:'<div  class="{%class%}"></div>',options:{format:"mm:ss"},_create:function(a,f,d,b){if("string"==typeof b.format)b.format=b.format.split(":");d=function(){a.html(g(f.prop("duration"),b.format))};f.bind("durationchange emptied",d);a.bind("updatetimeformat",
d).jmeProp("format",b.format)}});a.jme.defineProp("countdown",{set:function(c,f){var d=a.jme.data(c);d.countdown=!!f;a(c).triggerHandler("updatetimeformat");d.player.triggerHandler("updatetimeformat");return"noDataSet"}});a.jme.registerPlugin("currenttime-display",{structure:'<div  class="{%class%}"></div>',options:{format:"mm:ss",countdown:!1},_create:function(a,f,d,b){if("string"==typeof b.format)b.format=b.format.split(":");d=function(){var d=f.prop("currentTime");b.countdown&&(d=(f.prop("duration")||
0)-d,0.7>d&&(d=0));a.html(g(d,b.format))};f.bind("timeupdate emptied durationchange",d);a.bind("updatetimeformat",d).jmeProp("format",b.format)}});a.jme.fullscreen=function(){var c,f,d={supportsFullScreen:!1,isFullScreen:function(){return!1},requestFullScreen:function(b){c=[];a(b).parentsUntil("body").each(function(){var b=a.curCSS(this,"position"),d=this.scrollLeft,e=this.scrollTop,g;f={elemStyle:this.style,elem:this};if("static"!==b)g=!0,f.pos=f.elemStyle.position,this.style.position="static";if(d)g=
!0,f.left=d;if(e)g=!0,f.top=e;g&&c.push(f)});f=null},cancelFullScreen:function(){c&&a.each(c,function(a,b){if("pos"in b)b.elemStyle.position=b.pos;if(b.left)b.elem.scrollLeft=b.left;if(b.top)b.elem.scrollTop=b.top})},eventName:"fullscreenchange",prefix:""},b="webkit moz o ms khtml".split(" ");if("undefined"!=typeof document.cancelFullScreen)d.supportsFullScreen=!0;else for(var e=0,g=b.length;e<g;e++)if(d.prefix=b[e],"undefined"!=typeof document[d.prefix+"CancelFullScreen"]){d.supportsFullScreen=!0;
break}if(d.supportsFullScreen)d.eventName=d.prefix+"fullscreenchange",d.isFullScreen=function(){switch(d.prefix){case "":return document.fullScreen;case "webkit":return document.webkitIsFullScreen;default:return document[d.prefix+"FullScreen"]}},d.requestFullScreen=function(a){return""===d.prefix?a.requestFullScreen():a[this.prefix+"RequestFullScreen"]()},d.cancelFullScreen=function(){return""===d.prefix?document.cancelFullScreen():document[this.prefix+"CancelFullScreen"]()};return d}();a.jme.defineProp("fullscreen",
{set:function(c,f){var d=a.jme.data(c);if(!d||!d.player)return"noDataSet";if(f){if(d.player.hasClass(a.jme.classNS+"player-fullscreen"))return"noDataSet";d.scrollPos={top:a(window).scrollTop(),left:a(window).scrollLeft()};a(document).unbind(".jmefullscreen").bind("keydown.jmefullscreen",function(a){if(27==a.keyCode)return d.player.jmeProp("fullscreen",!1),!1});try{a.jme.fullscreen.requestFullScreen(d.player[0])}catch(b){}a("html").addClass(a.jme.classNS+"has-media-fullscreen");d.player.addClass(a.jme.classNS+
"player-fullscreen");d.media.addClass(a.jme.classNS+"media-fullscreen");a.jme.fullscreen.supportsFullScreen&&a(document).bind(a.jme.fullscreen.eventName+".jmefullscreen",function(b){var e=a.jme.fullscreen.isFullScreen();e&&c==b.target?a(c).triggerHandler("playerdimensionchange",["fullscreen"]):e||d.player.jmeProp("fullscreen",!1)});d.player.triggerHandler("playerdimensionchange",["fullwindow"]);d.media.callProp("play")}else{if(!d.player.hasClass(a.jme.classNS+"player-fullscreen"))return"noDataSet";
a(document).unbind(".jmefullscreen");a("html").removeClass(a.jme.classNS+"has-media-fullscreen");d.player.removeClass(a.jme.classNS+"player-fullscreen");d.media.removeClass(a.jme.classNS+"media-fullscreen");try{a.jme.fullscreen.cancelFullScreen()}catch(e){}d.player.triggerHandler("playerdimensionchange");d.scrollPos&&(a(window).scrollTop(d.scrollPos.top),a(window).scrollLeft(d.scrollPos.left),delete d.scrollPos)}return"noDataSet"},get:function(c){if((c=a.jme.data(c))&&c.player)return!c.player.hasClass(a.jme.classNS+
"player-fullscreen")?!1:a.jme.fullscreen.isFullScreen()||"fullwindow"}});a.jme.registerPlugin("fullscreen",{pseudoClasses:{enter:"state-enterfullscreen",exit:"state-exitfullscreen"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"enter fullscreen / exit fullscreen",_create:function(c,f,d){var b=a.jme.getButtonText(c,[this.pseudoClasses.enter,this.pseudoClasses.exit]),f=function(){b(d.hasClass(a.jme.classNS+"player-fullscreen")?
1:0)};d.bind("playerdimensionchange",f);c.bind(c.is("select")?"change":"click",function(){d.jmeProp("fullscreen",!d.hasClass(a.jme.classNS+"player-fullscreen"))});f()}});a.jme.registerPlugin("poster-display",{structure:"<div />",options:{},_create:function(c,f){var d=function(){var b=f.prop("poster");b?c.html('<span></span><img src="'+b+'" class="'+a.jme.classNS+'poster-image" />'):c.empty()};f.bind("emptied",d);d()}})})(jQuery);
