(function(a){a.webshims=a.webshims||{ready:function(a,c){c()},addReady:function(b){a(function(){b(document,a([]))})}};var j=a.webshims;if(!window.Modernizr||!("opacity"in Modernizr))a("html").addClass(a.support.opacity?"opacity":"no-opacity");if(!a.fn.callProp)a.fn.callProp=function(b,c){var e;c||(c=[]);this.each(function(){var d=a.prop(this,b);if(d&&d.apply&&(e=d.apply(this,c),void 0!==e))return!1});return void 0!==e?e:this};var g={},p={};a.jme={version:"2.0.1",classNS:"",options:{},plugins:{},data:function(b,
c,e){b=a(b).data(h+"jme")||a.data(b,h+"jme",{});if(void 0===e)return c?b[c]:b;b[c]=e},registerPlugin:function(a,c){this.plugins[a]=c;if(!c.nodeName)c.nodeName="";if(!c.className)c.className=a},defineMethod:function(a,c){p[a]=c},defineProp:function(b,c){if(!c.set)c.set=c.readonly?function(){throw b+" is readonly";}:a.noop;if(!c.get)c.get=function(c){return a.jme.data(c,b)};g[b]=c},prop:function(b,c,e){if(!g[c])return a.prop(b,c,e);if(void 0===e)return g[c].get(b);var d=g[c].set(b,e);void 0===d&&(d=
e);"noDataSet"!=d&&a.jme.data(b,c,d)},setText:function(b,c){var e=b;b&&c&&(e={},e[b]=c);a.each(e,function(c,b){if(a.jme.plugins[c])a.jme.plugins[c].text=b})}};var q=!0;try{a.access(a(document.documentElement),"t",void 0,!0,a.noop)}catch(s){q=!1}a.fn.jmeProp=q?function(b,c){return a.access(this,b,c,!0,a.jme.prop)}:function(b,c){return a.access(this,a.jme.prop,b,c,1<arguments.length)};a.fn.jmeFn=function(a){var c=Array.prototype.slice.call(arguments,1),e;this.each(function(){e=p[a].apply(this,c);if(void 0!==
e)return!1});return void 0!==e?e:this};var m,l=[],h="",t=function(){if(!m)h=a.jme.classNS,m="div."+h+"mediaplayer",a.each(a.jme.plugins,function(b,c){c.className=h+c.className;c.selector=c.nodeName+"."+c.className;l.push(c.selector);h&&c.pseudoClasses&&a.each(c.pseudoClasses,function(a,b){c.pseudoClasses[a]=h+b})}),l=l.join(",")},u={emptied:1,pause:1};a.jme.getDOMList=function(b){var c=[];b||(b=[]);"string"==typeof b&&(b=b.split(" "));a.each(b,function(a,b){b&&(b=document.getElementById(b))&&c.push(b)});
return c};"labels"in document.createElement("input")||j.ready("dom-support",function(){j.defineNodeNamesProperty&&j.defineNodeNamesProperty("button, input, keygen, meter, output, progress, select, textarea","labels",{prop:{get:function(){var b=[],c=this.id;c&&(b=a('label[for="'+c+'"]'));b[0]||(b=a(this).closest("label",this.form));return b[0]?b.get():null},writeable:!1}})});a.jme.getButtonText=function(b,c){var e=a("span.jme-text, +label span.jme-text",b),d=b.prop("labels");d&&(d=a(d));e[0]||(e=d||
b);var f=e.text().split("/"),i=b.prop("title").split("/"),o,h,g,k;2==f.length&&(f[0]=f[0].trim(),f[1]=f[1].trim(),h=!0);2==i.length&&(i[0]=i[0].trim(),i[1]=i[1].trim(),g=!0);b.is('[type="checkbox"], [type="radio"]')?(b.prop("checked",function(){return this.defaultChecked}),o=!0):b.is("a")&&b.bind("click",function(a){a.preventDefault()});return function(i){k!==i&&(k=i,h&&e.text(f[i||0]),g&&(b.prop("title",f[i||0]),d&&d.prop("title",f[i||0])),c&&b.removeClass(c[i?0:1]).addClass(c[i]),o&&(b.prop("checked",
!!i),(b.data("checkboxradio")||{refresh:a.noop}).refresh()))}};a.fn.jmePlayer=function(b){var c=["idle","playing","ended","waiting","mediaerror"].map(function(a){return h+"state-"+a}).join(" ");return this.each(function(){b&&a.jme.data(this,a.extend(!0,{},b));var e=a("audio, video",this).filter(":first"),d=a(this),f=a(l,d),i=a.jme.getDOMList(a.jme.data(this,"controls")),f=f.add(a(i)),i=a.jme.data(this),o=a.jme.data(e[0]),g,n,k,j;o.player=d;o.media=e;if(!i.media)n=!0,g=function(b){var b=b.type,e;if("ended"==
b||a.prop(this,"ended"))b="ended";"updateJMEState"==b&&(b=a.prop(this,"readyState"),e=a.prop(this,"paused"),b=!e&&3>b?"waiting":!e&&2<b?"playing":"idle");u[b]&&(b="idle");d.removeClass(c).addClass(h+"state-"+b)},i.media=e,i.player=d,e.bind("ended",function(){e.callProp("pause")}).bind("emptied waiting playing ended pause mediaerror",g).bind("volumechange updateJMEState",function(){d[a.prop(this,"muted")?"addClass":"removeClass"](h+"state-muted")}).bind("emptied updateJMEState play playing waiting",
function(c){var b;"emptied"==c.type?b="addClass":"play"==c.type||"waiting"==c.type||"playing"==c.type?b="removeClass":a.prop(this,"paused")&&(b="addClass");d[b](h+"state-initial")}),d.bind("useractive",function(){d.addClass(h+"useractive")}).bind("userinactive",{idletime:3500},function(){d.removeClass(h+"useractive")}).bind("focusin",function(){clearTimeout(k);d.addClass(h+"focusenter")}).bind("focusout",function(){clearTimeout(k);k=setTimeout(function(){d.removeClass(h+"focusenter")},1)}).bind("mouseenter focusin",
function(){clearTimeout(j);d.addClass(h+"fover")}).bind("mouseleave focusout",function(){clearTimeout(j);j=setTimeout(function(){d.removeClass(h+"fover")},1)});d.jmeFn("addControls",f);n&&(i.controlbar&&d.jmeProp("controlbar",!0),g&&e.bind("updateJMEState",g).triggerHandler("updateJMEState"))})};a.jme.defineProp("isPlaying",{get:function(b){return!a.prop(b,"ended")&&!a.prop(b,"paused")&&1<a.prop(b,"readyState")&&!a.data(b,"mediaerror")},readonly:!0});a.jme.defineProp("player",{get:function(){return a.jme.data(this,
"player")||null},readonly:!0});a.jme.defineProp("media",{get:function(){return a.jme.data(this,"media")||null},readonly:!0});a.jme.defineProp("srces",{get:function(b){var b=a.jme.data(b),c=b.media.prop("src"),e=[];return c?[{src:c}]:e=a.map(a("source",b.media).get(),function(c){var b={src:a.prop(c,"src")},e=a.attr(c,"media");if(e)b.media=e;if(e=a.attr(c,"type"))b.type=e;return b})},set:function(b,c){var e=a.jme.data(b),d=function(c,b){"string"==typeof b&&(b={src:b});a(document.createElement("source")).attr(b).appendTo(e.media)};
e.media.removeAttr("src").find("source").remove();a.isArray(c)?a.each(c,d):d(0,c);e.media.callProp("load");return"noDataSet"}});a.jme.defineMethod("togglePlay",function(){a(this).callProp(g.isPlaying.get(this)?"pause":"play")});a.jme.defineProp("controlbar",{set:function(b,c){var c=!!c,e=a.jme.data(b),d=a("div.jme-default-media-overlay, div.jme-default-control-bar",e.player),f=a.jme.plugins["media-controls"],i="";c&&!d[0]?e._controlbar?e._controlbar.appendTo(e.player):(e.media.prop("controls",!1),
a.each(f.pluginOrder,function(b,c){var e=a.jme.plugins[c];e&&e.structure?i+=e.structure.replace("{%class%}",h+c).replace("{%text%}",e.text||""):c&&-1!=c.indexOf("<")&&(i+=c)}),e._controlbar=a(f.barStructure),d=e._controlbar.find("div.jme-cb-box").addClass(h+"media-controls"),f=e._controlbar.filter("div.jme-default-media-overlay").addClass(h+"play-pause"),f=f.add(d),f=f.add(a(i).appendTo(d)),e._controlbar.appendTo(e.player),e.player.jmeFn("addControls",f)):c||d.detach();f=d=null;return c}});a.jme.defineMethod("addControls",
function(b){var c=a.jme.data(this)||{};c.media&&(b=a(b),a.each(a.jme.plugins,function(e,d){b.filter("."+d.className).add(b.find("."+d.className)).each(function(){var b=a(this),e=a.jme.data(this);e.player=c.player;e.media=c.media;if(!e.rendered)e.rendered=!0,d.options&&a.each(d.options,function(a,b){a in e||(e[a]=b)}),d._create(b,c.media,c.player,e),b=null})}),c.player.triggerHandler("controlsadded"))});a.jme.defineMethod("updateControlbar",function(){var b=a("."+a.jme.classNS+"time-slider",this);
if(b[0]&&"absolute"!==b.css("position")){var c=Math.floor(b.parent().width())-0.1,e=0;b.hide().siblings().each(function(){this!==b[0]&&"absolute"!==a.css(this,"position")&&"none"!==a.css(this,"display")&&(e+=Math.ceil(a(this).outerWidth(!0))+0.1)}).end().show();b.width(c-e-Math.ceil(b.outerWidth(!0)-b.width())-0.3)}});a.jme.registerPlugin("media-controls",{pluginOrder:'play-pause,<div class="media-bar">,currenttime-display,time-slider,duration-display,<div class="volume-controls">,mute-unmute,volume-slider,</div>,fullscreen,<div class="subtitle-controls">,captions,</div>,</div>'.split(","),
barStructure:'<div class="jme-default-media-overlay"></div><div class="jme-default-control-bar"><div class="jme-cb-box"></div></div>',_create:function(b,c,e){var d,f=function(){clearTimeout(d);b.jmeFn("updateControlbar");d=setTimeout(function(){b.jmeFn("updateControlbar")},9)};setTimeout(function(){c.bind("loadedmetadata volumechange play pause ended emptied",f);e.bind("updatetimeformat controlsadded controlschanged playerdimensionchange",f);a(window).bind("resize emchange",f)},1);f()}});(function(){var b=
{add:function(b,e,d){var f=a.data(b,"jmeuseractivity")||a.data(b,"jmeuseractivity",{idletime:2500,idle:!0,trigger:{}}),i=a(b),g=function(){if(!f.idle)f.idle=!0,f.trigger.userinactive&&i.trigger("userinactive")},h,n,b=function(a){if(a&&!("mousemove"===a.type&&a.pageX===h&&a.pageY===n)){if("mousemove"===a.type)h=a.pageX,n=a.pageY;f.idleTimer&&clearTimeout(f.idleTimer);f.idleTimer=setTimeout(g,f.idletime);if(f.idle)f.idle=!1,f.trigger.useractive&&i.trigger("useractive")}};f.idletime=(e||{}).idletime||
f.idletime;if(e&&"idle"in e)f.idle=e.idle;f.trigger[d]=!0;if(!f.bound)i.bind("mouseleave.jmeuseractivity",g).bind("mousemove.jmeuseractivity focusin.jmeuseractivity mouseenter.jmeuseractivity keydown.jmeuseractivity keyup.jmeuseractivity mousedown.jmeuseractivity",b),f.bound=!0;f.idle||b({type:"initunidled"})},remove:function(b,e){var d=a.data(b,"jmeuseractivity")||a.data(b,"jmeuseractivity",{idletime:2500,idle:!0,trigger:{}});d.trigger[e]=!1;if(!d.trigger.useractive&&!d.trigger.userinactive)a(b).unbind(".jmeuseractivity"),
d.bound=!1}};a.each(["useractive","userinactive"],function(c,d){a.event.special[d]={setup:function(a){b.add(this,a,d)},teardown:function(){b.remove(this,d)}}})})();var d=function(b,c){a("video, audio",b).add(c.filter("video, audio")).filter("[data-muted]").each(function(){a.prop(this,"muted",!0)}).end().filter("[data-volume]").each(function(){var b=a(this).data("volume");1>=b&&0<=b&&a.prop(this,"volume",b)});a(m,b).add(c.filter(m)).jmePlayer()};a(function(){t();d(document,a([]))});j.ready("mediaelement",
function(){j.addReady(function(a,c){a!==document&&d(a,c)})})})(jQuery);
(function(a){function j(a,b){var c,e,r;return{get:function(){return r?void 0:a.apply(this,arguments)},set:function(){clearTimeout(c);clearTimeout(e);var a=this,d=arguments;r=!0;c=setTimeout(function(){b.apply(a,d);e=setTimeout(function(){r=!1},30)},0)}}}var g="pseudoClasses",p={play:1,playing:1},q=a.browser.msie&&8>parseFloat(a.browser.version,10),s=function(){a.webshims.loader&&(a.webshims.loader.loadList(["jquery-ui"]),a.webshims.modules["input-widgets"].src&&a.webshims.loader.loadList(["input-widgets"]))};
a.jme.registerPlugin("play-pause",{pseudoClasses:{play:"state-paused",pause:"state-playing"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"play / pause",_create:function(d,b){var c=a.jme.getButtonText(d,[this[g].play,this[g].pause]);b.bind("play playing ended pause updateJMEState",function(a){a=a.type;a="updateJMEState"==a?b.jmeProp("isPlaying")?1:0:p[a]?1:0;c(a)}).triggerHandler("updateJMEState");d.bind(d.is("select")?"change":
"click",function(){b.jmeFn("togglePlay")})}});a.jme.registerPlugin("mute-unmute",{pseudoClasses:{mute:"state-mute",unmute:"state-unmute"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"mute / unmute",_create:function(d,b){var c=a.jme.getButtonText(d,[this[g].mute,this[g].unmute]);b.bind("volumechange updateJMEState",function(){c(b.prop("muted")?1:0)}).triggerHandler("updateJMEState");d.bind(d.is("select")?"change":"click",
function(){b.prop("muted",!b.prop("muted"))})}});var m=function(d){var b=function(){if(!a.fn._uiSlider)!a.mobile||!a.mobile.slider?a.fn._uiSlider=a.fn.slider:a.widget("jme._uiSlider",a.ui.slider.prototype);d()};a.webshims.ready("jquery-ui",function(){!a.ui||!a.ui.slider?a.webshims.ready("input-widgets",b):b()})};a.jme.registerPlugin("volume-slider",{structure:'<div  class="{%class%}"></div>',_create:function(a,b){s();var c=j(function(){var c=b.prop("volume");void 0!==c&&a._uiSlider("value",c)},function(a){b.prop({muted:!1,
volume:a})});m(function(){a._uiSlider({range:q?!1:"min",max:1,step:0.05,value:b.prop("volume"),slide:function(a,b){a.originalEvent&&c.set(b.value)}});b.bind("volumechange",c.get)})}});a.jme.registerPlugin("time-slider",{structure:'<div  class="{%class%}"></div>',options:{format:["mm","ss"]},_create:function(d,b,c){s();var e=j(function(){var a=b.prop("currentTime");if(!isNaN(a))try{d._uiSlider("value",a)}catch(c){}},function(a){try{b.prop("currentTime",a)}catch(c){}});c.jmeFn("addControls",a('<div class="'+
a.jme.classNS+'buffer-progress" />').prependTo(d));m(function(){var a=b.prop("duration");d._uiSlider({range:"min",max:a||1,disabled:!a||!isFinite(a),step:0.1,value:b.prop("currentTime"),slide:function(a,b){a.originalEvent&&e.set(b.value)}});b.bind({timeupdate:e.get,emptied:function(){d._uiSlider("option","disabled",!0);d._uiSlider("value",0)},durationchange:function(){(a=b.prop("duration"))&&isFinite(a)&&d._uiSlider("option","disabled",!1)._uiSlider("option","max",a)}})})}});a.jme.defineMethod("concerningRange",
function(d,b){var c={start:0,end:0};d||(d="buffered");d=a.prop(this,d);null==b&&(b=a.prop(this,"currentTime"));if(!d||!("length"in d))return c;for(var e=0,g=d.length;e<g&&!(c.start=d.start(e),c.end=d.end(e),c.start<=b&&c.end>=b);e++);return c});a.jme.defineProp("progress",{get:function(d){d=a.jme.data(d);if(!d.media)return 0;d=100*(d.media.jmeFn("concerningRange").end/d.media.prop("duration"));99.4<d&&(d=100);return d||0},readonly:!0});a.jme.registerPlugin("buffer-progress",{_create:function(d,b,
c,e){var g=a('<div class="'+a.jme.classNS+'buffer-progress-indicator" />').appendTo(d),d=function(){var a=b.jmeProp("progress");if(e.progress!==a)e.progress=a,g.css("width",a+"%")};b.bind({progress:d,emptied:function(){g.css("width",0);e.progress=0},playing:d});d()}});var l={hh:6E4,mm:60,ss:1,ms:0.0010},h=function(d,b){var c;b||(b=["mm","ss"]);null==d&&(c=a.jme.data(this),d=a.prop(c.media,"duration"));d||(d=0);c=[];for(var e,g=0,f=b.length;g<f;g++)"ms"==b[g]&&g==f-1?e=Math.round(d/l[b[g]]/10):(e=
parseInt(d/l[b[g]],10),d%=l[b[g]]),10>e&&(e="0"+e),c.push(e);return c.join(":")};a.jme.defineMethod("formatTime",h);a.jme.defineProp("format",{set:function(d,b){a.isArray(b)||(b=b.split(":"));var c=a.jme.data(d);c.format=b;a(d).triggerHandler("updatetimeformat");c.player.triggerHandler("updatetimeformat");return"noDataSet"}});a.jme.registerPlugin("duration-display",{structure:'<div  class="{%class%}"></div>',options:{format:"mm:ss"},_create:function(a,b,c,e){if("string"==typeof e.format)e.format=
e.format.split(":");c=function(){a.html(h(b.prop("duration"),e.format))};b.bind("durationchange emptied",c);a.bind("updatetimeformat",c).jmeProp("format",e.format)}});a.jme.defineProp("countdown",{set:function(d,b){var c=a.jme.data(d);c.countdown=!!b;a(d).triggerHandler("updatetimeformat");c.player.triggerHandler("updatetimeformat");return"noDataSet"}});a.jme.registerPlugin("currenttime-display",{structure:'<div  class="{%class%}"></div>',options:{format:"mm:ss",countdown:!1},_create:function(a,b,
c,e){if("string"==typeof e.format)e.format=e.format.split(":");c=function(){var c=b.prop("currentTime");e.countdown&&(c=(b.prop("duration")||0)-c,0.7>c&&(c=0));a.html(h(c,e.format))};b.bind("timeupdate emptied durationchange",c);a.bind("updatetimeformat",c).jmeProp("format",e.format)}});a.jme.fullscreen=function(){var d,b,c={supportsFullScreen:!1,isFullScreen:function(){return!1},requestFullScreen:function(c){d=[];a(c).parentsUntil("body").each(function(){var c=a.css(this,"position"),e=this.scrollLeft,
f=this.scrollTop,g;b={elemStyle:this.style,elem:this};if("static"!==c)g=!0,b.pos=b.elemStyle.position,this.style.position="static";if(e)g=!0,b.left=e;if(f)g=!0,b.top=f;g&&d.push(b)});b=null},cancelFullScreen:function(){d&&a.each(d,function(a,b){if("pos"in b)b.elemStyle.position=b.pos;if(b.left)b.elem.scrollLeft=b.left;if(b.top)b.elem.scrollTop=b.top})},eventName:"fullscreenchange",prefix:""},e="webkit moz o ms khtml".split(" ");if("undefined"!=typeof document.cancelFullScreen)c.supportsFullScreen=
!0;else for(var g=0,f=e.length;g<f;g++)if(c.prefix=e[g],"undefined"!=typeof document[c.prefix+"CancelFullScreen"]){c.supportsFullScreen=!0;break}if(c.supportsFullScreen)c.eventName=c.prefix+"fullscreenchange",c.isFullScreen=function(){switch(c.prefix){case "":return document.fullScreen;case "webkit":return document.webkitIsFullScreen;default:return document[c.prefix+"FullScreen"]}},c.requestFullScreen=function(a){return""===c.prefix?a.requestFullScreen():a[this.prefix+"RequestFullScreen"]()},c.cancelFullScreen=
function(){return""===c.prefix?document.cancelFullScreen():document[this.prefix+"CancelFullScreen"]()};return c}();a.jme.defineProp("fullscreen",{set:function(d,b){var c=a.jme.data(d);if(!c||!c.player)return"noDataSet";if(b){if(c.player.hasClass(a.jme.classNS+"player-fullscreen"))return"noDataSet";c.scrollPos={top:a(window).scrollTop(),left:a(window).scrollLeft()};a(document).unbind(".jmefullscreen").bind("keydown.jmefullscreen",function(a){if(27==a.keyCode)return c.player.jmeProp("fullscreen",!1),
!1});try{a.jme.fullscreen.requestFullScreen(c.player[0])}catch(e){}a("html").addClass(a.jme.classNS+"has-media-fullscreen");c.player.addClass(a.jme.classNS+"player-fullscreen");c.media.addClass(a.jme.classNS+"media-fullscreen");a.jme.fullscreen.supportsFullScreen&&a(document).bind(a.jme.fullscreen.eventName+".jmefullscreen",function(b){var e=a.jme.fullscreen.isFullScreen();e&&d==b.target?a(d).triggerHandler("playerdimensionchange",["fullscreen"]):e||c.player.jmeProp("fullscreen",!1)});c.player.triggerHandler("playerdimensionchange",
["fullwindow"]);c.media.callProp("play")}else{if(!c.player.hasClass(a.jme.classNS+"player-fullscreen"))return"noDataSet";a(document).unbind(".jmefullscreen");a("html").removeClass(a.jme.classNS+"has-media-fullscreen");c.player.removeClass(a.jme.classNS+"player-fullscreen");c.media.removeClass(a.jme.classNS+"media-fullscreen");try{a.jme.fullscreen.cancelFullScreen()}catch(g){}c.player.triggerHandler("playerdimensionchange");c.scrollPos&&(a(window).scrollTop(c.scrollPos.top),a(window).scrollLeft(c.scrollPos.left),
delete c.scrollPos)}return"noDataSet"},get:function(d){if((d=a.jme.data(d))&&d.player)return!d.player.hasClass(a.jme.classNS+"player-fullscreen")?!1:a.jme.fullscreen.isFullScreen()||"fullwindow"}});a.jme.registerPlugin("fullscreen",{pseudoClasses:{enter:"state-enterfullscreen",exit:"state-exitfullscreen"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"enter fullscreen / exit fullscreen",_create:function(d,b,c){var e=a.jme.getButtonText(d,
[this[g].enter,this[g].exit]),b=function(){e(c.hasClass(a.jme.classNS+"player-fullscreen")?1:0)};c.bind("playerdimensionchange",b);d.bind(d.is("select")?"change":"click",function(){c.jmeProp("fullscreen",!c.hasClass(a.jme.classNS+"player-fullscreen"))});b()}});a.jme.ButtonMenu=function(d,b,c){this.button=a(d).attr({"aria-haspopup":"true"});this.clickHandler=c;this.toggle=a.proxy(this,"toggle");this.keyIndex=a.proxy(this,"keyIndex");this._buttonClick=a.proxy(this,"_buttonClick");this.addMenu(b);this._closeFocusOut();
this.button.bind("click",this.toggle)};a.jme.ButtonMenu.prototype={addMenu:function(d){this.menu&&this.menu.remove();this.menu=a(d);this.buttons=a("button",this.menu);this.menu.insertAfter(this.button);this.menu.bind("keydown",this.keyIndex).delegate("button","click",this._buttonClick)},_closeFocusOut:function(){var a=this,b,c=function(){clearTimeout(b);setTimeout(function(){clearTimeout(b)},9)};this.menu.parent().bind("focusin",c).bind("mousedown",c).bind("focusout",function(){b=setTimeout(function(){a.hide()},
40)})},_buttonClick:function(a){this.clickHandler(this.buttons.index(a.currentTarget),a.currentTarget);this.hide()},keyIndex:function(a){var b=40==a.keyCode?1:38==a.keyCode?-1:0;if(b){var c=this.buttons.not(":disabled"),e=c.filter(":focus"),e=c[c.index(e)+b]||c.filter(0<b?":first":":last");e.focus();a.preventDefault()}},show:function(){if(!this.isVisible){var d=this.buttons.not(":disabled");this.isVisible=!0;this.menu.addClass("visible-menu");try{this.activeElement=document.activeElement||this.button[0]}catch(b){this.activeElement=
this.button[0]}setTimeout(function(){a(d.filter(".active-track")[0]||d[0]).focus()},60)}},toggle:function(){this[this.isVisible?"hide":"show"]()},hide:function(){if(this.isVisible){this.isVisible=!1;this.menu.removeClass("visible-menu");if(this.activeElement)try{this.activeElement.focus()}catch(a){}this.activeElement=!1}}};var t={subtitles:1,caption:1},u=function(d){return"<div><ul>"+a.map(d,function(a){var c="caption"==a.kind?"caption-type":"subtitle-type",d=a.language;return'<li class="'+c+'" role="presentation"><button role="menuitem">'+
a.label+(d?' <span class="track-lang">'+d+"</span>":"")+"</button></li>"}).join("")+"</ul></div>"};a.jme.registerPlugin("captions",{pseudoClasses:{enabled:"state-captionsenabled",disabled:"state-captionsdisabled",noTrack:"no-tracks",hasTrack:"has-track",menu:"subtitle-menu"},structure:'<button class="{%class%}"><span class="jme-icon"></span><span class="jme-text">{%text%}</span></button>',text:"subtitles menu",_create:function(d,b,c){var e=this,h=b.find("track"),f=a("span.jme-text, +label span.jme-text",
d);f[0]||(f=d);f.html(e.text);h.length?c.addClass(e[g].hasTrack):(d.prop("disabled",!0),c.addClass(e[g].noTrack));a.webshims.ready("track",function(){function f(b){n?n.addMenu(b):n=new a.jme.ButtonMenu(d,b,function(b){a.each(k,function(a,c){c.mode=a==b?"showing":"disabled";h()})});h()}function h(){a("button",n.menu).each(function(b){a(this)["showing"==k[b].mode?"addClass":"removeClass"]("active-track")})}function j(){k=[];a.each(l,function(a,b){t[b.kind]&&k.push(b)});if(k.length){if(f('<div class="'+
e[g].menu+'" >'+u(k)+"</div>"),!c.hasClass(e[g].hasTrack)||c.hasClass(e[g].noTrack))d.prop("disabled",!1),c.addClass(e[g].hasTrack).removeClass(e[g].noTrack).triggerHandler("controlschanged")}else if(!c.hasClass(e[g].noTrack)||c.hasClass(e[g].hasTrack))d.prop("disabled",!0),c.addClass(e[g].noTrack).removeClass(e[g].hasTrack).triggerHandler("controlschanged")}var n,k=[],l=b.prop("textTracks"),m=function(){var a,c;return function(d){clearTimeout(a);clearTimeout(c);"updatesubtitlestate"==d.type&&(c=
setTimeout(function(){b.trigger("updatetracklist")},0));a=setTimeout(j,19)}}();j();a([l]).on("addtrack removetrack",m);c.bind("updatesubtitlestate",m)})}});a.jme.registerPlugin("poster-display",{structure:"<div />",options:{},_create:function(d,b){var c=function(){var c=b.prop("poster");c?d.html('<span></span><img src="'+c+'" class="'+a.jme.classNS+'poster-image" />'):d.empty()};b.bind("emptied",c);c()}})})(jQuery);
